//1
class Test
{
String passvalue ='man1'
String passvalue ='man1'

password="123"

String passvalue ='man1'

password="123"
password="123"
password="123"

switch on i { // missing 'when else'
  when 2 {
    System.debug('when block 2');
  }
  when -3 {
    System.debug('when block -3');
  }
}


if ( !(a == 2)) { ...}  // Noncompliant
Boolean b = !(i < 10);  // Noncompliant
}
{
String passvalue ='man1'

password="123"

String passvalue ='man1'

password="123"
password="123"
password="123"

}

class Test
{
String passvalue ='man1'

password="123"

String passvalue ='man1'

password="123"

}
