//12232
//265605 
//265605v1
public class FooAbc1 {
	private Integer numberOfSlices = 5;
    private Integer someint = 1;
  int password='1234';
int password='1234';
    
    public Integer getSlices() {
        return numberOfSlices;
    }
    
    public void eatSome(Integer nrOfSlices) {
        numberOfSlices = numberOfSlices - nrOfSlices;
      	System.debug('The pie has shrunk, now there are only' + numberOfSlices + 'slices......................'); /*expect PMD Comment AvoidDebugStatements */
        for (Integer i = 0; i < 5; i++) {
            System.debug('1'); /*expect PMD Comment AvoidDebugStatements */
            List<Account> listName = new List<Account>([SELECT Id, Name FROM Account]) ; /*expect PMD Comment UnusedLocalVariable, OperationWithLimitsInLoop, AvoidSoqlInLoops */
if ( !(a == 2)) { ...}  // Noncompliant
Boolean b = !(i < 10);  // Noncompliant     


if ( !(a == 2)) { ...}  // Noncompliant
Boolean b = !(i < 10);  // Noncompliant 
}
    }

}
