name: Your Workflow Name

on:
  pull_request:
    branches:
      - dev # Replace 'target-branch-name' with the name of the branch you're targeting
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'dev'
    steps:
      - name: dev branh trigger condition
        # Your steps here
