name: Add Labels to PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add label
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
