name: Build
on:
  pull_request:
    branches:
      - dev
      - main
jobs:
  devcondition:
    name: devcheck
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'dev'
    steps:
      - name: dev condition check pass
